module.exports = {
  CHECK_LAUNCHER_VERSION: 'check-launcher-version',
  CLOSE_LAUNCHER: 'close-launcher',
  TOGGLE_SETTINGS: 'toggle-settings',
  OPEN_LINK: 'open-link',
  GET_VK_LINK: 'get-vk-link',
  GET_DISCORD_LINK: 'get-discord-link',
  GET_SERVER_HASHLIST: 'get-server-hashlist',
  GET_FILES_HASH: 'get-files-hash',
  GET_LIST_OF_CHANGED_FILES: 'get-list-of-changed-files',
  GET_FILES_SUMMARY_SIZE: 'get-files-summary-size',
  DOWNLOAD_LIST_OF_FILES: 'download-list-of-files',
  GET_ONLINE_COUNT: 'get-online-count',
  GET_LAST_NEWS: 'get-last-news',
  START_EXE: 'start-exe',
};